/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type { StructureData, StructureDataInterface } from "../StructureData";

const _abi = [
  {
    inputs: [],
    name: "MATUREROUND",
    outputs: [
      {
        internalType: "uint8",
        name: "",
        type: "uint8",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "PRICE_PRECISION",
    outputs: [
      {
        internalType: "uint8",
        name: "",
        type: "uint8",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

const _bytecode =
  "0x609c610038600b82828239805160001a607314602b57634e487b7160e01b600052600060045260246000fd5b30600052607381538281f3fe7300000000000000000000000000000000000000003014608060405260043610603d5760003560e01c806395082d25146042578063f747e17714605f575b600080fd5b6049600481565b60405160ff909116815260200160405180910390f35b604960018156fea264697066735822122012f74c0f2efb617032f9c1b637385b1b28d94dea80729299dc05541fbf8dea2b64736f6c63430008040033";

export class StructureData__factory extends ContractFactory {
  constructor(
    ...args: [signer: Signer] | ConstructorParameters<typeof ContractFactory>
  ) {
    if (args.length === 1) {
      super(_abi, _bytecode, args[0]);
    } else {
      super(...args);
    }
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<StructureData> {
    return super.deploy(overrides || {}) as Promise<StructureData>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): StructureData {
    return super.attach(address) as StructureData;
  }
  connect(signer: Signer): StructureData__factory {
    return super.connect(signer) as StructureData__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): StructureDataInterface {
    return new utils.Interface(_abi) as StructureDataInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): StructureData {
    return new Contract(address, _abi, signerOrProvider) as StructureData;
  }
}
